package nl.mprog.rens.vinylcountdown;

import java.io.Serializable;
import java.sql.Date;
import java.text.SimpleDateFormat;

/**
 * Created by Rens on 24/01/2017.
 */

public class Message implements Serializable{

    String buyOffer;
    String sellOffer;
    UserProfile senderProfile;
    UserProfile receiverProfile;
    String messageContent;
    String time;
    String priceType;
    String messageType;
    String offerID;
    String senderID;
    String receiverID;

    public String getMessageType() {
        return messageType;
    }

    public String getReceiverID() {
        return receiverID;
    }

    public void setReceiverID(String receiverID) {
        this.receiverID = receiverID;
    }

    public String getSenderID() {
        return senderID;
    }

    public void setSenderID(String senderID) {
        this.senderID = senderID;
    }

    public boolean isRead() {
        return read;
    }

    public void setRead(boolean read) {
        this.read = read;
    }

    boolean read;

    // This is the format of the response messages generated in the inbox.
    public void messageReply(String messageType, String buyOffer, String sellOffer, UserProfile sender, String senderID, UserProfile receiver, String receiverID){

        // Set the message according to the type of response (rejected/accepted)!
        if (messageType.equals("accept")){
            this.messageContent = "I would like to accept your offer of " + buyOffer + " for " + sellOffer + ", please contact me via my email address.";
        }
        if (messageType.equals("reject")){
            this.messageContent = "I respectfully decline your offer of " + buyOffer + " for " + sellOffer + ", feel free to make another request!";
        }

        // Set the time at which the message was sent:
        this.time = new SimpleDateFormat("dd-MM-yyyy HH:mm").format(new java.util.Date());
        this.senderID = senderID;
        this.receiverID = receiverID;
        this.setRead(false);
        this.messageType = messageType;
        this.senderProfile = sender;
        this.receiverProfile = receiver;
        this.buyOffer = buyOffer;
    }

    // These are the messages generated by the marketplace.
    public void messageMarket(String messageType, String priceType, String buyOffer, String sellOffer, String offerID, UserProfile sender, String senderID, UserProfile receiver, String receiverID){

        // Create a message according to the right advertisement priceType.
        if (priceType.equals("Price")){

            this.messageContent = "Hello, I saw your advertisement for " + buyOffer + " and I would buy it for $" + sellOffer + ".";
        }
        else if (priceType.equals("Bidding from")){

            this.messageContent = "Hello, I saw your advertisement for " + buyOffer + " and I bid $" + sellOffer + ".";
        }
        else if (priceType.equals("Trade")){

            this.messageContent = "Hello, I saw your advertisement for " + buyOffer + " and I would like to trade you for " + sellOffer + ".";
        }

        this.senderProfile = sender;
        this.receiverProfile = receiver;
        this.priceType = priceType;
        this.buyOffer = buyOffer;
        this.sellOffer = sellOffer;
        this.offerID = offerID;
        this.senderID = senderID;
        this.receiverID = receiverID;
        this.messageType = messageType;
        this.setRead(false);

        // Set the time at which the message was sent:
        this.time = new SimpleDateFormat("dd-MM-yyyy HH:mm").format(new java.util.Date());
    }

    // Empty constructor for database writing.
    public Message(){}

    // Getters and setters.
    public String getBuyOffer() {
        return buyOffer;
    }public String getOfferID() {
        return offerID;
    }

    public void setOfferID(String offerID) {
        this.offerID = offerID;
    }

    public void setBuyOffer(String buyOffer) {
        this.buyOffer = buyOffer;
    }

    public String getSellOffer() {
        return sellOffer;
    }

    public void setSellOffer(String sellOffer) {
        this.sellOffer = sellOffer;
    }

    public UserProfile getSender() {
        return senderProfile;
    }

    public void setSender(UserProfile sender) {
        this.senderProfile = sender;
    }

    public UserProfile getReceiver() {
        return receiverProfile;
    }

    public void setReceiver(UserProfile receiver) {
        this.receiverProfile = receiver;
    }

    public String getMessageContent() {
        return messageContent;
    }

    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getType() {
        return priceType;
    }

    public void setType(String priceType) {
        this.priceType = priceType;
    }
}
